language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

before_script:
  - composer install

script:
  - ant phplint
  - ant phpcs
  - ant phpunit

notifications:
    email:
        - gregor@klevze.com
